### ISSUE TITLE
Create v5 extension configuration

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-extension-seed#47]
We need a v5 branch which imports the PF v5 alphas, as well as proper configuration to make that the new primary development branch and enable releasing alphas from it.

**Comment by wise-king-sullyman** [comment]
As discussed at standup one day, I don't think we really want to have extensions being based on alpha versions of PF by default do we?

I feel like this issue should be moved to the sprint during which PF5 is actually slated to go GA, and just update it to consume PF5 at that point.

**Comment by dlabaj** [comment]
@wise-king-sullyman I'm going to work on this if that's okay.

**Comment by nicolethoen** [comment]
closing in favor of new issue
